<?php
// ============================================================
//  config.php — Configuration principale
//  Les réglages dynamiques sont dans settings.json.
//  Chaque galerie est un fichier JSON dans galleries/.
// ============================================================

define('SETTINGS_FILE',  __DIR__ . '/settings.json');
define('GALLERIES_DIR',  __DIR__ . '/galleries');

define('APP_VERSION', '1.3.0');

// ── Réglages globaux ────────────────────────────────────────

function load_settings(): array {
    if (file_exists(SETTINGS_FILE)) {
        $data = json_decode(file_get_contents(SETTINGS_FILE), true);
        if (is_array($data)) return $data;
    }
    return [
        'phpsessid'  => '12345678_aBcDeFgHiJkLmNoPqRsTuVwXyZ0123456789abcdef', // Valeur par défaut (à remplacer par l'utilisateur)
        'admin_hash' => password_hash('admin', PASSWORD_DEFAULT),
    ];
}

function save_settings(array $data): bool {
    return file_put_contents(SETTINGS_FILE, json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE)) !== false;
}

$SETTINGS = load_settings();
define('PIXIV_PHPSESSID', $SETTINGS['phpsessid']);

// ── Remember-me token ────────────────────────────────────────

define('REMEMBER_COOKIE', 'pxv_rm');
define('REMEMBER_TTL',    7 * 24 * 3600); // 7 jours

/**
 * Génère et enregistre un token de reconnexion.
 * Pose le cookie côté client, stocke le hash côté serveur.
 */
function remember_set(): void {
    global $SETTINGS;
    $token = bin2hex(random_bytes(32)); // 64 chars hex
    $SETTINGS['remember_hash'] = hash('sha256', $token);
    $SETTINGS['remember_exp']  = time() + REMEMBER_TTL;
    save_settings($SETTINGS);
    setcookie(REMEMBER_COOKIE, $token, [
        'expires'  => time() + REMEMBER_TTL,
        'path'     => '/',
        'secure'   => isset($_SERVER['HTTPS']),
        'httponly' => true,
        'samesite' => 'Lax',
    ]);
}

/**
 * Vérifie le cookie de reconnexion.
 * Retourne true et régénère un nouveau token si valide.
 */
function remember_check(): bool {
    global $SETTINGS;
    $token = $_COOKIE[REMEMBER_COOKIE] ?? '';
    if ($token === '') return false;
    $stored_hash = $SETTINGS['remember_hash'] ?? '';
    $stored_exp  = $SETTINGS['remember_exp']  ?? 0;
    if ($stored_hash === '' || time() > $stored_exp) return false;
    if (!hash_equals($stored_hash, hash('sha256', $token))) return false;
    // Token valide → rotation (évite le vol de token par replay)
    remember_set();
    return true;
}

/**
 * Supprime le token de reconnexion (déconnexion).
 */
function remember_clear(): void {
    global $SETTINGS;
    unset($SETTINGS['remember_hash'], $SETTINGS['remember_exp']);
    save_settings($SETTINGS);
    setcookie(REMEMBER_COOKIE, '', [
        'expires'  => time() - 3600,
        'path'     => '/',
        'secure'   => isset($_SERVER['HTTPS']),
        'httponly' => true,
        'samesite' => 'Lax',
    ]);
}

// ── Galeries ────────────────────────────────────────────────

/**
 * Valide un slug de galerie : a-z, 0-9, tirets, max 20 caractères.
 */
function is_valid_gallery_slug(string $slug): bool {
    return (bool) preg_match('/^[a-z0-9\-]{1,20}$/', $slug);
}

/**
 * Chemin vers le fichier JSON d'une galerie.
 */
function gallery_file(string $slug): string {
    return GALLERIES_DIR . '/' . $slug . '.json';
}

/**
 * Charge une galerie par son slug.
 * Retourne null si inexistante ou invalide.
 */
function load_gallery(string $slug): ?array {
    if (!is_valid_gallery_slug($slug)) return null;
    $file = gallery_file($slug);
    if (!file_exists($file)) return null;
    $data = json_decode(file_get_contents($file), true);
    return is_array($data) ? $data : null;
}

/**
 * Sauvegarde une galerie.
 */
function save_gallery(string $slug, array $data): bool {
    if (!is_dir(GALLERIES_DIR)) mkdir(GALLERIES_DIR, 0755, true);
    return file_put_contents(gallery_file($slug), json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE)) !== false;
}

/**
 * Supprime une galerie (JSON + PHP).
 */
function delete_gallery(string $slug): bool {
    $json = gallery_file($slug);
    $php  = GALLERIES_DIR . '/' . $slug . '.php';
    $ok   = true;
    if (file_exists($json)) $ok = unlink($json) && $ok;
    if (file_exists($php))  $ok = unlink($php)  && $ok;
    return $ok;
}

/**
 * Crée (ou recrée) le fichier PHP d'une galerie depuis le template.
 */
function create_gallery_php(string $slug): bool {
    $template = GALLERIES_DIR . '/_template.php';
    $dest     = GALLERIES_DIR . '/' . $slug . '.php';
    if (!file_exists($template)) {
        // Génère un template minimal si absent
        $content = '<?php require_once __DIR__ . \'/_template.php\'; ?>';
        // En réalité on crée un stub autonome
        $content = "<?php\n// Auto-generated by Pixivorama\n"
            . "require_once __DIR__ . '/../config.php';\n"
            . "\$slug    = basename(__FILE__, '.php');\n"
            . "\$gallery = load_gallery(\$slug);\n"
            . "if (!\$gallery) { http_response_code(404); echo '404'; exit; }\n"
            . "// Inclure le template de rendu\n"
            . "include __DIR__ . '/_template.php';\n";
        return file_put_contents($dest, $content) !== false;
    }
    return copy($template, $dest);
}

/**
 * Retourne la liste de toutes les galeries sous forme de tableau
 * ['slug' => ..., 'title' => ..., 'characters' => [...]]
 * triées par ordre alphabétique de slug.
 */
function list_galleries(): array {
    if (!is_dir(GALLERIES_DIR)) return [];
    $files   = glob(GALLERIES_DIR . '/*.json') ?: [];
    $results = [];
    foreach ($files as $file) {
        $slug = basename($file, '.json');
        if (!is_valid_gallery_slug($slug)) continue;
        $data = json_decode(file_get_contents($file), true);
        if (!is_array($data)) continue;
        $results[] = array_merge(['slug' => $slug], $data);
    }
    usort($results, fn($a, $b) => strcmp($a['slug'], $b['slug']));
    return $results;
}

// ── Constantes Pixiv ────────────────────────────────────────

define('PIXIV_DEFAULT_PER_PAGE', 28);
define('PIXIV_DEFAULT_ORDER',    'popular_d');
define('PIXIV_DEFAULT_MODE',     'safe');
define('PIXIV_AI_TYPE',          1);

// ── Préférences d'affichage admin ───────────────────────────

/**
 * Retourne les préférences de galerie pour l'admin connecté.
 * Fusionne les valeurs sauvegardées avec les valeurs par défaut publiques.
 */
function get_admin_gallery_defaults(array $settings): array {
    $saved = $settings['gallery_defaults'] ?? [];
    return [
        'order'    => in_array($saved['order']    ?? '', ['popular_d', 'date_d'], true)
                        ? $saved['order'] : PIXIV_DEFAULT_ORDER,
        'period'   => in_array($saved['period']   ?? '', ['', 'day', 'week', 'month', '6month', 'year'], true)
                        ? $saved['period'] : '',
        'per_page' => in_array((int)($saved['per_page'] ?? 0), [28, 56], true)
                        ? (int)$saved['per_page'] : PIXIV_DEFAULT_PER_PAGE,
        'mode'     => in_array($saved['mode']     ?? '', ['safe', 'r18', 'all'], true)
                        ? $saved['mode'] : PIXIV_DEFAULT_MODE,
    ];
}