<?php
// ============================================================
//  includes/galleries.php — Fonctions CRUD des galeries
//  et helpers associés.
//
//  Dépend de : config.php (pour GALLERIES_DIR, save_settings(),
//              PIXIV_DEFAULT_*)
// ============================================================

// ── Schéma ──────────────────────────────────────────────────

/** Version courante du schéma JSON des galeries. */
define('GALLERY_SCHEMA_VERSION', 1);

// ── Validation ──────────────────────────────────────────────

/**
 * Valide un slug de galerie : a-z, 0-9, tirets, max 20 caractères.
 */
function is_valid_gallery_slug(string $slug): bool {
    return (bool) preg_match('/^[a-z0-9\-]{1,20}$/', $slug);
}

// ── Accès fichiers ───────────────────────────────────────────

/**
 * Chemin vers le fichier JSON d'une galerie.
 */
function gallery_file(string $slug): string {
    return GALLERIES_DIR . '/' . $slug . '.json';
}

// ── Lecture ─────────────────────────────────────────────────

/**
 * Charge une galerie par son slug.
 * Retourne null si inexistante ou invalide.
 */
function load_gallery(string $slug): ?array {
    if (!is_valid_gallery_slug($slug)) return null;
    $file = gallery_file($slug);
    if (!file_exists($file)) return null;
    $data = json_decode(file_get_contents($file), true);
    return is_array($data) ? $data : null;
}

// ── Écriture ─────────────────────────────────────────────────

/**
 * Sauvegarde une galerie.
 * Ajoute automatiquement `schema_version` si absent.
 */
function save_gallery(string $slug, array $data): bool {
    if (!is_dir(GALLERIES_DIR)) mkdir(GALLERIES_DIR, 0755, true);
    $data['schema_version'] = $data['schema_version'] ?? GALLERY_SCHEMA_VERSION;
    return file_put_contents(
        gallery_file($slug),
        json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE)
    ) !== false;
}

// ── Suppression ──────────────────────────────────────────────

/**
 * Supprime une galerie (JSON + PHP).
 */
function delete_gallery(string $slug): bool {
    $json = gallery_file($slug);
    $php  = GALLERIES_DIR . '/' . $slug . '.php';
    $ok   = true;
    if (file_exists($json)) $ok = unlink($json) && $ok;
    if (file_exists($php))  $ok = unlink($php)  && $ok;
    return $ok;
}

// ── Génération PHP ───────────────────────────────────────────

/**
 * Crée (ou recrée) le fichier PHP d'une galerie depuis le template.
 */
function create_gallery_php(string $slug): bool {
    $template = GALLERIES_DIR . '/_template.php';
    $dest     = GALLERIES_DIR . '/' . $slug . '.php';
    if (!file_exists($template)) {
        $content = "<?php\n// Auto-generated by Pixivorama\n"
            . "require_once __DIR__ . '/../config.php';\n"
            . "\$slug    = basename(__FILE__, '.php');\n"
            . "\$gallery = load_gallery(\$slug);\n"
            . "if (!\$gallery) { http_response_code(404); echo '404'; exit; }\n"
            . "include __DIR__ . '/_template.php';\n";
        return file_put_contents($dest, $content) !== false;
    }
    return copy($template, $dest);
}

// ── Liste ────────────────────────────────────────────────────

/**
 * Retourne la liste de toutes les galeries publiques.
 */
function list_galleries(): array {
    if (!is_dir(GALLERIES_DIR)) return [];
    $files   = glob(GALLERIES_DIR . '/*.json') ?: [];
    $results = [];
    foreach ($files as $file) {
        $slug = basename($file, '.json');
        if (!is_valid_gallery_slug($slug)) continue;
        $data = json_decode(file_get_contents($file), true);
        if (!is_array($data)) continue;
        $results[] = array_merge(['slug' => $slug], $data);
    }
    usort($results, fn($a, $b) => strcmp($a['slug'], $b['slug']));
    return $results;
}

// ── Préférences d'affichage admin ────────────────────────────

/**
 * Retourne les préférences d'affichage de l'admin avec valeurs par défaut.
 */
function get_admin_gallery_defaults(array $settings): array {
    $saved = $settings['gallery_defaults'] ?? [];
    return [
        'order'    => in_array($saved['order']    ?? '', ['popular_d', 'date_d'], true)
                        ? $saved['order'] : PIXIV_DEFAULT_ORDER,
        'period'   => in_array($saved['period']   ?? '', ['', 'day', 'week', 'month', '6month', 'year'], true)
                        ? $saved['period'] : '',
        'per_page' => in_array((int)($saved['per_page'] ?? 0), [28, 56], true)
                        ? (int)$saved['per_page'] : PIXIV_DEFAULT_PER_PAGE,
        'mode'     => in_array($saved['mode']     ?? '', ['safe', 'r18', 'all'], true)
                        ? $saved['mode'] : PIXIV_DEFAULT_MODE,
    ];
}
